### PR TITLE
Added a prop to form and names to fields for netlify form handling

### LINKED ISSUE #4: Connect contact us form to backend API

### PR DESCRIPTION
**Pull request by jkhoeini**
Fixes #4 
I added the required props based on netlify's docs. We should test to see if it actually works, after deployment.

### CODE REVIEW

**Comment by pomle** [comment]
Oh shoot, this has become outdated due to other changes. Do you mind rebasing it @mkhoeini?

**Review by pomle — APPROVED** [review]
Feel free to merge

**Review by pomle — CHANGES_REQUESTED** [review]
Sorry, my first approval was too hasty.

I noticed it does not work. Submitting takes you to a 404 page. 
Can you check why?

I hooked up the Form in the Netlify settings so should send me an email.

**Comment by jkhoeini** [comment]
> Sorry, my first approval was too hasty.
> 
> I noticed it does not work. Submitting takes you to a 404 page.
> Can you check why?
> 
> I hooked up the Form in the Netlify settings so should send me an email.

The problem appears to be with how React interacts with the page. I'll send a fix shortly.

**Comment by pomle** [comment]
It works!

**Pull request merged**
